// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOnCkKNfQVD2XtzbFI09-KY4fmTtJ_MOs',
    appId: '1:709523799199:web:51842908e044476ac0b6aa',
    messagingSenderId: '709523799199',
    projectId: 'webapp-3a726',
    authDomain: 'webapp-3a726.firebaseapp.com',
    databaseURL: 'https://webapp-3a726-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webapp-3a726.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYTz078h5jW_OKiLMxyrCVsLRoRFyfwRg',
    appId: '1:709523799199:android:1061072bd3183a39c0b6aa',
    messagingSenderId: '709523799199',
    projectId: 'webapp-3a726',
    databaseURL: 'https://webapp-3a726-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webapp-3a726.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRNjJZEz7aFkDOk7dZnk0ql98xt9jD1k8',
    appId: '1:709523799199:ios:792aaa11621e568dc0b6aa',
    messagingSenderId: '709523799199',
    projectId: 'webapp-3a726',
    databaseURL: 'https://webapp-3a726-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webapp-3a726.appspot.com',
    iosClientId: '709523799199-7st5ou9ug1lrs5agu46mkn2rmgjbdj1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRNjJZEz7aFkDOk7dZnk0ql98xt9jD1k8',
    appId: '1:709523799199:ios:792aaa11621e568dc0b6aa',
    messagingSenderId: '709523799199',
    projectId: 'webapp-3a726',
    databaseURL: 'https://webapp-3a726-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webapp-3a726.appspot.com',
    iosClientId: '709523799199-7st5ou9ug1lrs5agu46mkn2rmgjbdj1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );
}
